version: '3.8'

services:
  teste-unifor:
    image: ttuca123/testeunifor2025:latest
    container_name: teste-unifor
    networks:
      - net-unifor
    ports:
      - "8180:8180"
    restart: always
networks:
  net-unifor:
    external: true
