version: '3.8'

services:
  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    image: quarkus/code-with-quarkus-legacy-jar
    ports:
      - "8180:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
      - KEYCLOAK_URL=http://keycloak:8080/auth
    depends_on:
      - keycloak
    networks:
      - quarkus-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - quarkus-network

networks:
  quarkus-network:
    driver: bridge
