--Mapeamento dos scripts ddl para criação das tabelas do banco

  create table professor (
        matricula bigint generated by default as identity,
        ativo boolean,
        cpf varchar(255),
        data_admissao date,
        fone varchar(255),
        nome varchar(255),
        primary key (matricula)
    );

  create table disciplina (
        id_disciplina bigint generated by default as identity,
        ativo boolean,
        creditos integer,
        nome varchar(255),
        primary key (id_disciplina)
    );

    create table curso (
        id_curso bigint generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        primary key (id_curso)
    );

    create table aluno (
        matricula bigint generated by default as identity,
        ativo boolean,
        cpf varchar(255),
        data_admissao date,
        fone varchar(255),
        nome varchar(255),
        primary key (matricula)
    );

    create table usuario (
        id_usuario int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
        ativo bool NULL,
        cpf varchar(255) NULL,
        fone varchar(255) NULL,
        nome varchar(255) NULL,
        CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
    );


    -- public.aluno_matriculado definição

-- Drop table

-- DROP TABLE public.aluno_matriculado;

CREATE TABLE aluno_matriculado (
	id_alunomatriculado int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	matricula int8 NULL,
	id_turma int8 NULL,
	CONSTRAINT aluno_matriculado_pkey PRIMARY KEY (id_alunomatriculado)
);


-- public.aluno_matriculado chaves estrangeiras

ALTER TABLE public.aluno_matriculado ADD CONSTRAINT fkhd9cujjmyma8ebnb3v5nbmqjs FOREIGN KEY (matricula) REFERENCES public.aluno(matricula);
ALTER TABLE public.aluno_matriculado ADD CONSTRAINT fkrwtqdtpr9ckh70f9tufcauh80 FOREIGN KEY (id_turma) REFERENCES public.turma(id_turma);


-- public.matriz_curricular definição

-- Drop table

-- DROP TABLE public.matriz_curricular;

CREATE TABLE public.matriz_curricular (
	id_curso int8 NULL,
	id_disciplina int8 NULL,
	id_matrizcurricular int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_professor int8 NULL,
	CONSTRAINT matriz_curricular_pkey PRIMARY KEY (id_matrizcurricular)
);


-- public.matriz_curricular chaves estrangeiras

ALTER TABLE public.matriz_curricular ADD CONSTRAINT fk2l9f7ou8f4ebaedvid2r64v94 FOREIGN KEY (id_curso) REFERENCES public.curso(id_curso);
ALTER TABLE public.matriz_curricular ADD CONSTRAINT fk82eo8stlt5f1sd2sanahdj4yl FOREIGN KEY (id_professor) REFERENCES public.professor(matricula);
ALTER TABLE public.matriz_curricular ADD CONSTRAINT fkn4cmgricsm1x48qj0n3dd1e72 FOREIGN KEY (id_disciplina) REFERENCES public.disciplina(id_disciplina);